
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

name: Build and deploy GH Pages

jobs:

  test-rust:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        cd rust-tests
        cargo test --verbose --all-features

  build:
    runs-on: ubuntu-latest
    depends-on: test-rust
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages

          TOKEN: ${{ secrets.GITHUB_TOKEN }}